version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - forcetypeassert
    - bodyclose
    - noctx
    - errorlint

issues:
  exclude-use-default: false
